import { harborStoryMock } from "../company-story";
import { createCompanyStory } from "../company-story";
import { createDecisionEngine, harborDecisionEngineMock } from "../decision-engine";
import { harborDocumentsMock, createDocumentIntelligence } from "../document-intelligence";
import { createOffice, createSeat, leadershipOfficeMock } from "../executive-office";
import { createExecutiveMemory, founderMemoryMock } from "../executive-memory";
import {
  createCompanyIdentity,
  founderIdentityMock,
  harborIdentityMock,
} from "../identity";
import { createKnowledgeGraphState, harborKnowledgeMock } from "../knowledge-graph";
import { createMissionEngine, harborMissionMock } from "../mission-engine";
import {
  createOperatingHealth,
  harborHealthMock,
  portfolioHealthMock,
} from "../operating-health";
import {
  createExecutiveBriefing,
  emptyRecommendationEngine,
} from "../recommendation/model";
import { emptyPolicyEngine } from "../policy/model";
import { createRiskIntelligence, harborRiskMock } from "../risk-intelligence";
import { createVentureGenome, harborGenomeMock } from "../venture-genome";
import { createVenture, hydrateVentureIntelligence } from "./model";
import type { Venture, VentureIntelligenceCore } from "./types";

function quietOffice() {
  return createOffice({
    enabled: true,
    posture: "Seated.",
    worldLine: "This company is covered by the leadership floor.",
    desks: [
      {
        seat: createSeat("founder", true, "clear", "Seated"),
        brief: {
          headline: "Covered by the leadership floor.",
          body: "Company-level desks defer to the Executive Office.",
          focus: "Follow the floor brief.",
        },
        primaryAction: { label: "Open the floor", href: "/agents" },
        correspondence: [],
      },
    ],
  });
}

const harbor: Venture = createVenture({
  identity: harborIdentityMock,
  genome: harborGenomeMock,
  story: harborStoryMock,
  executiveOffice: quietOffice(),
  decisions: harborDecisionEngineMock,
  memory: createExecutiveMemory([]),
  knowledge: harborKnowledgeMock,
  mission: harborMissionMock,
  health: harborHealthMock,
  documents: harborDocumentsMock,
  risk: harborRiskMock,
  recommendations: emptyRecommendationEngine(),
  policy: emptyPolicyEngine(),
});

const atlas: Venture = createVenture({
  identity: createCompanyIdentity({
    id: "atlas",
    slug: "atlas-legal",
    name: "Atlas Legal",
    href: "/ventures",
    foundedAt: "2025-01-08T09:00:00.000Z",
    category: "SaaS",
    stage: "Seed",
    owner: "M. Reid",
    hqSummary: "Atlas Legal is open. This is the command surface for the company.",
  }),
  genome: createVentureGenome({
    thesis: "Atlas Legal is a SaaS company at seed, pointed at installing the operating system.",
    category: "SaaS",
    stage: "Seed",
    goal: "Install the operating system",
    posture: "ai-native",
    risk: "focused",
    motion: "Cadence first: one source of truth, one weekly review.",
    cadence: "Daily Executive Office briefing, weekly founder review.",
  }),
  story: createCompanyStory({
    origin: "Atlas Legal was founded to make contract intake a queue, not a heroics function.",
    thesis: "The product is judgement, fenced.",
    promise: "Classify and queue. Never draft.",
    chapter: "The queue is the product",
    excerpt: "Atlas stalls when the founder redesigns instead of reviewing.",
    tension: "Twenty minutes unblocks the week.",
    featured: false,
  }),
  executiveOffice: quietOffice(),
  decisions: createDecisionEngine([
    {
      id: "atlas-clauses",
      ventureId: "atlas",
      company: "Atlas Legal",
      companyHref: "/ventures",
      ownerRoleId: "counsel",
      question:
        "Review Atlas’s two ambiguous clause types yourself, or escalate to counsel?",
      title: "Atlas clause review",
      recommendation:
        "Review yourself. Counsel adds two days and no new judgement the intake agent cannot wait for.",
      costOfInaction: "The queue stalls; the Executive Office looks idle.",
      decideBy: "Today",
      actionLabel: "Review clauses",
      actionHref: "/agents",
      status: "upcoming",
      briefing: true,
    },
    {
      id: "gc2",
      ventureId: "atlas",
      company: "Atlas Legal",
      companyHref: "/ventures",
      ownerRoleId: "counsel",
      question: "May the Atlas agent draft?",
      title: "Atlas agent may not draft",
      recommendation: "Classify and queue only.",
      costOfInaction: "Liability leaves the human review fence.",
      decideBy: "Two sprints ago",
      actionLabel: "Hold the fence",
      actionHref: "/agents/counsel",
      status: "resolved",
      briefing: false,
      ruling: "Classify and queue only.",
      result:
        "Liability stays with human review. The stall today is that review, not the agent.",
      resolvedOn: "Two sprints ago",
    },
    {
      id: "ct2",
      ventureId: "atlas",
      company: "Atlas Legal",
      companyHref: "/ventures",
      ownerRoleId: "cto",
      question: "What is Atlas agent scope?",
      title: "Atlas agent scope",
      recommendation: "Intake only. No drafting.",
      costOfInaction: "The agent becomes a writer.",
      decideBy: "Two sprints ago",
      actionLabel: "Hold scope",
      actionHref: "/agents/cto",
      status: "resolved",
      briefing: false,
      ruling: "Intake only. No drafting.",
      result: "The agent is reliable inside that fence.",
      resolvedOn: "Two sprints ago",
    },
  ]),
  memory: createExecutiveMemory([
    {
      id: "ctm1",
      ventureId: "atlas",
      ownerRoleId: "cto",
      recalledFrom: "Two sprints ago",
      title: "Atlas does not draft",
      note: "You and counsel agreed the agent classifies and queues. It does not write.",
      implication: "Do not expand scope to look busy.",
      briefing: false,
      desk: true,
    },
    {
      id: "gcm1",
      ventureId: "atlas",
      ownerRoleId: "counsel",
      recalledFrom: "Two sprints ago",
      title: "Ambiguity is reviewed in slices",
      note: "The founder asked for windows, not a legal redesign.",
      implication: "Two clauses. Then the queue moves.",
      briefing: false,
      desk: true,
    },
  ]),
  knowledge: createKnowledgeGraphState({
    nodes: [
      {
        id: "atlas-node",
        kind: "venture",
        label: "Atlas Legal",
        properties: { slug: "atlas-legal" },
      },
    ],
    edges: [],
  }),
  mission: createMissionEngine({
    today: {
      title: "Unblock two clause types",
      ask: "Unblock two clause types. Nothing else.",
      whyNow: "The intake queue is the constraint.",
      ifDeferred: "The Executive Office looks idle.",
      timeNeeded: "20 minutes",
      actionLabel: "Review clauses",
      actionHref: "/agents",
      attention: "today",
      founderAsk: "Unblock two clause types. Nothing else.",
      active: false,
    },
    sprint: {
      name: "Sprint 1",
      objective: "Clear the intake queue without a product redesign.",
      tasks: [
        { id: "t1", title: "Review two clause types", owner: "Founder" },
        { id: "t2", title: "Release the intake agent", owner: "CTO" },
      ],
    },
  }),
  health: createOperatingHealth({
    score: 61,
    label: "Risk",
    band: "risk",
    posture: "Queue backing up",
    summary: "Intake is stalled on two ambiguous clause types.",
    judgement: "Intake queue is backing up on two clause types.",
    ask: "Twenty minutes of review unblocks the agent.",
    briefWatch: true,
  }),
  documents: createDocumentIntelligence([]),
  risk: createRiskIntelligence({
    headline: "Legal ambiguity is being treated as an engineering defect.",
    signals: [
      {
        id: "atlas-r1",
        title: "Intake stall",
        severity: "high",
        band: "risk",
        summary: "Two clause types need founder judgement.",
        mitigation: "Review today. Do not retrain the model.",
      },
    ],
  }),
  recommendations: emptyRecommendationEngine(),
  policy: emptyPolicyEngine(),
});

const lumen: Venture = createVenture({
  identity: createCompanyIdentity({
    id: "lumen",
    slug: "lumen-labs",
    name: "Lumen Labs",
    href: "/ventures",
    foundedAt: "2024-11-02T09:00:00.000Z",
    category: "SaaS",
    stage: "Launch",
    owner: "S. Okonkwo",
    hqSummary: "Lumen Labs is open. This is the command surface for the company.",
  }),
  genome: createVentureGenome({
    thesis: "Lumen Labs is a SaaS company at launch, pointed at shipping the MVP.",
    category: "SaaS",
    stage: "Launch",
    goal: "Ship the MVP",
    posture: "ai-native",
    risk: "focused",
    motion: "Ship a narrow wedge, then instrument learning.",
    cadence: "Daily Executive Office briefing, weekly founder review.",
  }),
  story: createCompanyStory({
    origin: "Lumen Labs was founded to put a usable product in public.",
    thesis: "The product is already the story.",
    promise: "Ship a narrow wedge, then instrument learning.",
    chapter: "Ready, waiting on the line",
    excerpt:
      "Lumen’s product is already the story. What remains is a sentence the market can repeat. Every extra hour on copy is an hour the beta does not exist in public.",
    tension: "Lock the line. Let the launch write the rest.",
    featured: true,
  }),
  executiveOffice: quietOffice(),
  decisions: createDecisionEngine([
    {
      id: "lumen-positioning",
      ventureId: "lumen",
      company: "Lumen Labs",
      companyHref: "/ventures",
      ownerRoleId: "founder",
      question: "Lock Lumen’s launch line, or keep iterating copy?",
      title: "Lumen launch line",
      recommendation:
        "Lock it. Further copy cycles are taste, not risk. Public beta is Wednesday.",
      costOfInaction: "Launch day becomes a writing session.",
      decideBy: "Tomorrow morning",
      actionLabel: "Lock positioning",
      actionHref: "/ventures",
      status: "upcoming",
      briefing: true,
    },
    {
      id: "ct1",
      ventureId: "lumen",
      company: "Lumen Labs",
      companyHref: "/ventures",
      ownerRoleId: "cto",
      question: "Lumen launch freeze?",
      title: "Lumen launch freeze",
      recommendation: "No production changes after Monday.",
      costOfInaction: "A late infra change creates a launch you cannot explain.",
      decideBy: "Last week",
      actionLabel: "Hold freeze",
      actionHref: "/agents/cto",
      status: "resolved",
      briefing: false,
      ruling: "No production changes after Monday.",
      result: "Release train is clean. Copy is the remaining variable.",
      resolvedOn: "Last week",
    },
    {
      id: "cp1",
      ventureId: "lumen",
      company: "Lumen Labs",
      companyHref: "/ventures",
      ownerRoleId: "cpo",
      question: "Lumen beta scope?",
      title: "Lumen beta scope",
      recommendation: "No new surfaces. Existing product, public.",
      costOfInaction: "Wednesday slips.",
      decideBy: "Last week",
      actionLabel: "Hold scope",
      actionHref: "/agents/cpo",
      status: "resolved",
      briefing: false,
      ruling: "No new surfaces. Existing product, public.",
      result: "The team is building nothing that can slip Wednesday.",
      resolvedOn: "Last week",
    },
    {
      id: "cm1",
      ventureId: "lumen",
      company: "Lumen Labs",
      companyHref: "/ventures",
      ownerRoleId: "cmo",
      question: "Lumen launch assets?",
      title: "Lumen launch assets",
      recommendation: "One page. One line. No video.",
      costOfInaction: "Production becomes the bottleneck.",
      decideBy: "Last week",
      actionLabel: "Hold assets",
      actionHref: "/agents/cmo",
      status: "resolved",
      briefing: false,
      ruling: "One page. One line. No video.",
      result: "Production is light enough to change the line until tomorrow morning.",
      resolvedOn: "Last week",
    },
    {
      id: "ctu1",
      ventureId: "lumen",
      company: "Lumen Labs",
      companyHref: "/ventures",
      ownerRoleId: "cto",
      question: "Unfreeze Lumen infra after public beta?",
      title: "Unfreeze Lumen",
      recommendation: "Unfreeze Thursday, not Wednesday.",
      costOfInaction: "A hotfix during launch.",
      decideBy: "Thursday",
      actionLabel: "Wait until Thursday",
      actionHref: "/agents/cto",
      status: "upcoming",
      briefing: false,
    },
    {
      id: "cpu1",
      ventureId: "lumen",
      company: "Lumen Labs",
      companyHref: "/ventures",
      ownerRoleId: "cpo",
      question: "What is in sprint two after Lumen is public?",
      title: "Sprint two",
      recommendation: "Do not invent it before beta.",
      costOfInaction: "The backlog colonises launch day.",
      decideBy: "Next Monday",
      actionLabel: "Wait for beta",
      actionHref: "/agents/cpo",
      status: "upcoming",
      briefing: false,
    },
    {
      id: "cmu1",
      ventureId: "lumen",
      company: "Lumen Labs",
      companyHref: "/ventures",
      ownerRoleId: "cmo",
      question: "Lock Lumen’s launch line?",
      title: "Launch line",
      recommendation: "Ship the short line.",
      costOfInaction: "Beta users get a manifesto.",
      decideBy: "Tomorrow morning",
      actionLabel: "Lock the line",
      actionHref: "/agents/cmo",
      status: "upcoming",
      briefing: false,
    },
  ]),
  memory: createExecutiveMemory([
    {
      id: "cpm1",
      ventureId: "lumen",
      ownerRoleId: "cpo",
      recalledFrom: "Last week",
      title: "Beta is a sentence plus a product that already works",
      note: "You and CMO own the line. Engineering owns the freeze.",
      implication: "Do not invent a feature to feel ready.",
      briefing: false,
      desk: true,
    },
    {
      id: "cmm1",
      ventureId: "lumen",
      ownerRoleId: "cmo",
      recalledFrom: "Last week",
      title: "No theatre around Harbor",
      note: "The founder asked that price tests not become brand moments.",
      implication: "Copy stays plain. The learning is the point.",
      briefing: false,
      desk: true,
    },
  ]),
  knowledge: createKnowledgeGraphState({
    nodes: [
      {
        id: "lumen-node",
        kind: "venture",
        label: "Lumen Labs",
        properties: { slug: "lumen-labs" },
      },
    ],
    edges: [],
  }),
  mission: createMissionEngine({
    today: {
      title: "Lock the launch line",
      ask: "Lock the launch line. Do not join ops.",
      whyNow: "Public beta is Wednesday.",
      ifDeferred: "Launch day becomes a writing session.",
      timeNeeded: "Tomorrow morning",
      actionLabel: "Lock positioning",
      actionHref: "/ventures",
      attention: "this-week",
      founderAsk: "Lock the launch line. Do not join ops.",
      active: false,
    },
    sprint: {
      name: "Sprint 1",
      objective: "Put Lumen in public without new surfaces.",
      tasks: [
        { id: "t1", title: "Lock the line", owner: "CMO" },
        { id: "t2", title: "Hold the freeze", owner: "CTO" },
      ],
    },
  }),
  health: createOperatingHealth({
    score: 84,
    label: "Healthy",
    band: "healthy",
    posture: "Launch-ready",
    summary: "Launch-ready. Founder risk is over-involvement.",
    judgement: "Launch-ready. Founder risk is over-involvement.",
    ask: "Confirm positioning, then hold.",
    briefWatch: true,
  }),
  documents: createDocumentIntelligence([]),
  risk: createRiskIntelligence({
    headline: "The remaining risk is a sentence, not a sprint.",
    signals: [
      {
        id: "lumen-r1",
        title: "Copy delay",
        severity: "moderate",
        band: "healthy",
        summary: "Product is ready. The line is not locked.",
        mitigation: "CPO and CMO lock it without the founder in the room.",
      },
    ],
  }),
  recommendations: emptyRecommendationEngine(),
  policy: emptyPolicyEngine(),
});

const northwind: Venture = createVenture({
  identity: createCompanyIdentity({
    id: "northwind",
    slug: "northwind",
    name: "Northwind",
    href: "/ventures",
    foundedAt: "2023-06-01T09:00:00.000Z",
    category: "SaaS",
    stage: "Growth",
    owner: "A. Chen",
    hqSummary: "Northwind is open. This is the command surface for the company.",
  }),
  genome: createVentureGenome({
    thesis: "Northwind is a SaaS company at growth, pointed at scaling what already converts.",
    category: "SaaS",
    stage: "Growth",
    goal: "Win first customers",
    posture: "human-led",
    risk: "scaling",
    motion: "Prove a paid motion before expanding surface area.",
    cadence: "Weekly founder review until the Executive Office is seated.",
  }),
  story: createCompanyStory({
    origin: "Northwind is compounding.",
    thesis: "No founder decision improves the next 72 hours.",
    promise: "Leave it with A. Chen.",
    chapter: "Compounding",
    excerpt: "Northwind does not need this week.",
    tension: "Checking it recreates work that is already owned.",
    featured: false,
  }),
  executiveOffice: quietOffice(),
  decisions: createDecisionEngine([
    {
      id: "fd2",
      ventureId: "northwind",
      company: "Northwind",
      companyHref: "/ventures",
      ownerRoleId: "founder",
      question: "Who signs the vendor MSA?",
      title: "Northwind vendor MSA",
      recommendation: "Delegated to A. Chen.",
      costOfInaction: "The founder recreates owned work.",
      decideBy: "Last sprint",
      actionLabel: "Leave it",
      actionHref: "/dashboard",
      status: "resolved",
      briefing: false,
      ruling: "Delegated to A. Chen.",
      result: "Signature is no longer on this desk.",
      resolvedOn: "Last sprint",
    },
    {
      id: "gc-msa",
      ventureId: "northwind",
      company: "Northwind",
      companyHref: "/ventures",
      ownerRoleId: "counsel",
      question: "Northwind MSA?",
      title: "Northwind MSA",
      recommendation: "Delegated signature.",
      costOfInaction: "It returns to the founder desk.",
      decideBy: "Last sprint",
      actionLabel: "Leave it",
      actionHref: "/agents/counsel",
      status: "resolved",
      briefing: false,
      ruling: "Delegated signature.",
      result: "Not a founder item.",
      resolvedOn: "Last sprint",
    },
  ]),
  memory: createExecutiveMemory([]),
  knowledge: createKnowledgeGraphState({ nodes: [], edges: [] }),
  mission: createMissionEngine({
    today: {
      title: "Hold",
      ask: "No founder decision improves the next 72 hours.",
      whyNow: "It is already compounding.",
      ifDeferred: "Nothing of value is lost.",
      timeNeeded: "None",
      actionLabel: "Leave Northwind",
      actionHref: "/ventures",
      attention: "hold",
      founderAsk: "No founder decision improves the next 72 hours.",
      active: false,
    },
    sprint: {
      name: "Sprint 1",
      objective: "Do not spend founder attention here.",
      tasks: [],
    },
  }),
  health: createOperatingHealth({
    score: 91,
    label: "Healthy",
    band: "healthy",
    posture: "Compounding",
    summary: "Already compounding.",
    judgement: "Already compounding.",
    ask: "Hold.",
    briefWatch: false,
  }),
  documents: createDocumentIntelligence([]),
  risk: createRiskIntelligence({
    headline: "The risk is founder interruption.",
    signals: [],
  }),
  recommendations: emptyRecommendationEngine(),
  policy: emptyPolicyEngine(),
});

const kindred: Venture = createVenture({
  identity: createCompanyIdentity({
    id: "kindred",
    slug: "kindred",
    name: "Kindred",
    href: "/ventures",
    foundedAt: "2026-04-01T09:00:00.000Z",
    category: "Consumer",
    stage: "Explore",
    owner: "Sonny",
    hqSummary: "Kindred is open. This is the command surface for the company.",
  }),
  genome: createVentureGenome({
    thesis: "Kindred is a consumer company at idea, pointed at shipping the MVP.",
    category: "Consumer",
    stage: "Explore",
    goal: "Ship the MVP",
    posture: "human-led",
    risk: "exploratory",
    motion: "Ship a narrow wedge, then instrument learning.",
    cadence: "Weekly founder review until the Executive Office is seated.",
  }),
  story: createCompanyStory({
    origin: "Kindred is still a thesis.",
    thesis: "Do not pull the review forward.",
    promise: "Stay in notes, not in the board.",
    chapter: "Thesis",
    excerpt: "Kindred colonises attention the moment it has tickets.",
    tension: "Leave it scheduled.",
    featured: false,
  }),
  executiveOffice: quietOffice(),
  decisions: createDecisionEngine([]),
  memory: createExecutiveMemory([]),
  knowledge: createKnowledgeGraphState({ nodes: [], edges: [] }),
  mission: createMissionEngine({
    today: {
      title: "Hold the thesis review",
      ask: "Thesis review is scheduled. Do not pull it forward.",
      whyNow: "It is not the constraint.",
      ifDeferred: "Nothing of value is lost this week.",
      timeNeeded: "None",
      actionLabel: "Leave Kindred",
      actionHref: "/ventures",
      attention: "hold",
      founderAsk: "Thesis review is scheduled. Do not pull it forward.",
      active: false,
    },
    sprint: {
      name: "Sprint 1",
      objective: "Keep Kindred in discovery notes.",
      tasks: [],
    },
  }),
  health: createOperatingHealth({
    score: 70,
    label: "Watch",
    band: "watch",
    posture: "Exploratory",
    summary: "Thesis, not a sprint.",
    judgement: "Thesis, not a sprint.",
    ask: "Hold.",
    briefWatch: false,
  }),
  documents: createDocumentIntelligence([]),
  risk: createRiskIntelligence({
    headline: "Attention risk, not delivery risk.",
    signals: [],
  }),
  recommendations: emptyRecommendationEngine(),
  policy: emptyPolicyEngine(),
});

const leadershipDecisions = createDecisionEngine([
  {
    id: "cf1",
    ventureId: "harbor",
    company: "Harbor Pay",
    companyHref: "/ventures",
    ownerRoleId: "cfo",
    question: "Harbor raise this quarter?",
    title: "Harbor raise",
    recommendation: "Closed for the quarter.",
    costOfInaction: "Price is not learned.",
    decideBy: "Thursday",
    actionLabel: "Keep closed",
    actionHref: "/agents/cfo",
    status: "resolved",
    briefing: false,
    ruling: "Closed for the quarter.",
    result: "Investor process is dark. Price is the learning engine.",
    resolvedOn: "Thursday",
  },
  {
    id: "cf2",
    ventureId: "harbor",
    company: "Harbor Pay",
    companyHref: "/ventures",
    ownerRoleId: "cfo",
    question: "Loss band for commercial tests?",
    title: "Loss band for commercial tests",
    recommendation: "Four percent of monthly gross, two weeks, then stop.",
    costOfInaction: "Every test needs a new policy.",
    decideBy: "Last month",
    actionLabel: "Hold the band",
    actionHref: "/agents/cfo",
    status: "resolved",
    briefing: false,
    ruling: "Four percent of monthly gross, two weeks, then stop.",
    result: "Harbor’s experiment fits. No new policy required.",
    resolvedOn: "Last month",
  },
  {
    id: "cfu1",
    ventureId: "harbor",
    company: "Harbor Pay",
    companyHref: "/ventures",
    ownerRoleId: "cfo",
    question: "Extend or kill the Harbor test at day 14?",
    title: "Harbor test stop",
    recommendation: "Stop at day 14 unless the band is intact and learning is noisy.",
    costOfInaction: "The test becomes a new default price.",
    decideBy: "In 14 days, if approved",
    actionLabel: "Wait for the window",
    actionHref: "/agents/cfo",
    status: "upcoming",
    briefing: false,
  },
  {
    id: "co1",
    ventureId: "harbor",
    company: "Harbor Pay",
    companyHref: "/ventures",
    ownerRoleId: "coo",
    question: "Weekly operating rhythm?",
    title: "Weekly operating rhythm",
    recommendation: "Two founder windows. The rest of the floor runs without them.",
    costOfInaction: "The calendar fills itself.",
    decideBy: "This Monday",
    actionLabel: "Hold the rhythm",
    actionHref: "/agents/coo",
    status: "resolved",
    briefing: false,
    ruling: "Two founder windows. The rest of the floor runs without them.",
    result: "Calendars were cut. Exceptions now come through this office.",
    resolvedOn: "This Monday",
  },
  {
    id: "cou1",
    ventureId: "harbor",
    company: "Portfolio",
    companyHref: "/dashboard",
    ownerRoleId: "coo",
    question: "Keep or kill Friday portfolio review?",
    title: "Friday review",
    recommendation: "Kill it if Harbor and Atlas are closed.",
    costOfInaction: "It becomes a status meeting.",
    decideBy: "Friday",
    actionLabel: "Decide Friday",
    actionHref: "/agents/coo",
    status: "upcoming",
    briefing: false,
  },
  {
    id: "sa1",
    ventureId: "harbor",
    company: "Harbor Pay",
    companyHref: "/ventures",
    ownerRoleId: "sales",
    question: "Harbor outbound?",
    title: "Harbor outbound",
    recommendation: "Paused pending price.",
    costOfInaction: "The book sells last month’s offer.",
    decideBy: "This Monday",
    actionLabel: "Hold outbound",
    actionHref: "/agents/sales",
    status: "resolved",
    briefing: false,
    ruling: "Paused pending price.",
    result: "The book is frozen. No one is freelance-discounting.",
    resolvedOn: "This Monday",
  },
  {
    id: "sau1",
    ventureId: "harbor",
    company: "Harbor Pay",
    companyHref: "/ventures",
    ownerRoleId: "sales",
    question: "Which Harbor segments get the new price first?",
    title: "Harbor segments",
    recommendation: "Named list only, once the test is live.",
    costOfInaction: "The test leaks into the whole book.",
    decideBy: "When the test is live",
    actionLabel: "Wait for the test",
    actionHref: "/agents/sales",
    status: "upcoming",
    briefing: false,
  },
]);

const leadershipMemory = createExecutiveMemory([
  {
    id: "cfm1",
    ventureId: "harbor",
    ownerRoleId: "cfo",
    recalledFrom: "Thursday",
    title: "Capital is not the constraint",
    note: "The founder closed the raise so price could be learned in public.",
    implication: "Do not bring a deck. Bring the test.",
    briefing: false,
    desk: true,
  },
  {
    id: "com1",
    ventureId: "harbor",
    ownerRoleId: "coo",
    recalledFrom: "This Monday",
    title: "Founder time is rationed, not scheduled ad hoc",
    note: "You agreed no new recurring meetings this month.",
    implication: "If it is not Harbor or Atlas, it waits.",
    briefing: false,
    desk: true,
  },
  {
    id: "sam1",
    ventureId: "harbor",
    ownerRoleId: "sales",
    recalledFrom: "This Monday",
    title: "Do not sell around an unmade price",
    note: "You asked sales to wait rather than invent a bridge offer.",
    implication: "Idle pipeline is cheaper than a dirty test.",
    briefing: false,
    desk: true,
  },
]);

export const ventureIntelligenceMock: VentureIntelligenceCore =
  hydrateVentureIntelligence({
  founder: founderIdentityMock,
  office: leadershipOfficeMock,
  briefing: createExecutiveBriefing({
    preparedBy: "Prepared by VentureOS AI",
    headline: "",
    narrative: "",
    implications: [],
  }),
  health: portfolioHealthMock,
  memory: createExecutiveMemory([
    ...founderMemoryMock.records,
    ...leadershipMemory.records,
  ]),
  decisions: leadershipDecisions,
  recommendations: emptyRecommendationEngine(),
  policy: emptyPolicyEngine(),
  ventures: [harbor, atlas, lumen, northwind, kindred],
});

export const harborVentureMock =
  ventureIntelligenceMock.ventures.find((venture) => venture.identity.id === "harbor") ??
  harbor;
