import { existsSync, readdirSync, readFileSync, statSync } from "node:fs";
import { join } from "node:path";

const STATIC_LENGTH = /^-?\d+(\.\d+)?(px|rem|em)$/;
const FOUNDATION_BREAKPOINT =
  /--ids-foundation-breakpoint-([a-z]+)\s*:\s*([^;]+);/gi;
const ILLEGAL_CUSTOM_MEDIA = /@custom-media\b/i;
const ILLEGAL_MEDIA_VAR = /@(?:media|custom-media)[^{;]*var\s*\(/i;
const ILLEGAL_WIDTH_VAR = /width\s*>=\s*var\s*\(/i;
const ILLEGAL_THEME_BREAKPOINT_VAR = /--breakpoint-[a-z]+\s*:\s*var\s*\(/i;
const REQUIRED = ["sm", "md", "lg", "xl"] as const;

export type BreakpointMap = Record<(typeof REQUIRED)[number], string>;

export class TokenCssError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "TokenCssError";
  }
}

export function parseFoundationBreakpoints(css: string): BreakpointMap {
  const found: Record<string, string> = {};

  for (const match of css.matchAll(FOUNDATION_BREAKPOINT)) {
    const name = match[1];
    const value = match[2]?.trim() ?? "";
    if (!name) {
      continue;
    }
    if (value.includes("var(")) {
      throw new TokenCssError(
        `Foundation breakpoint --ids-foundation-breakpoint-${name} must be a static length, not ${value}. CSS variables are illegal inside media queries.`,
      );
    }
    if (!STATIC_LENGTH.test(value)) {
      throw new TokenCssError(
        `Foundation breakpoint --ids-foundation-breakpoint-${name} has unsupported value "${value}". Use px, rem, or em.`,
      );
    }
    found[name] = value;
  }

  for (const name of REQUIRED) {
    if (!found[name]) {
      throw new TokenCssError(
        `Foundation is missing static --ids-foundation-breakpoint-${name}.`,
      );
    }
  }

  return found as BreakpointMap;
}

export function emitBreakpointCss(breakpoints: BreakpointMap): string {
  const theme = REQUIRED.map(
    (name) => `  --breakpoint-${name}: ${breakpoints[name]};`,
  ).join("\n");

  return [
    "/* GENERATED by tokens/generate.ts from tokens/foundation.css. Do not edit. */",
    "",
    "@theme {",
    theme,
    "}",
    "",
  ].join("\n");
}

export function assertGeneratedCssIsValid(css: string, source = "css"): void {
  if (css.trim().length === 0) {
    throw new TokenCssError(`${source} is empty. Token pipeline produced no CSS.`);
  }
  if (ILLEGAL_CUSTOM_MEDIA.test(css)) {
    throw new TokenCssError(
      `${source} contains @custom-media. Next CSS parse warns on that at-rule. Emit static @theme breakpoint lengths only.`,
    );
  }
  if (ILLEGAL_MEDIA_VAR.test(css) || ILLEGAL_WIDTH_VAR.test(css)) {
    throw new TokenCssError(
      `${source} emits a media query that uses var(). LightningCSS cannot parse CSS variables in @media conditions. Breakpoints must be static lengths.`,
    );
  }
  if (ILLEGAL_THEME_BREAKPOINT_VAR.test(css)) {
    throw new TokenCssError(
      `${source} maps --breakpoint-* to var(). Tailwind inlines that into @media (width >= var(...)), which is invalid. Emit a resolved length from the token pipeline.`,
    );
  }
}

export function assertMediaQueriesAreStatic(css: string, source = "css"): void {
  assertGeneratedCssIsValid(css, source);
}

export function generateBreakpointCssFromFoundation(foundationCss: string): string {
  const breakpoints = parseFoundationBreakpoints(foundationCss);
  const emitted = emitBreakpointCss(breakpoints);
  assertGeneratedCssIsValid(emitted, "generated breakpoints.css");
  return emitted;
}

export function walkCssFiles(dir: string, files: string[] = []): string[] {
  if (!existsSync(dir)) {
    return files;
  }
  for (const entry of readdirSync(dir)) {
    const path = join(dir, entry);
    if (statSync(path).isDirectory()) {
      walkCssFiles(path, files);
      continue;
    }
    if (path.endsWith(".css")) {
      files.push(path);
    }
  }
  return files;
}

export function assertIdsCssTreeIsValid(idsRoot: string): void {
  const files = walkCssFiles(join(idsRoot, "tokens")).concat(
    walkCssFiles(join(idsRoot, "themes")),
  );
  for (const file of files) {
    assertGeneratedCssIsValid(readFileSync(file, "utf8"), file);
  }

  const index = readFileSync(join(idsRoot, "tokens/index.css"), "utf8");
  if (!index.includes("./generated/breakpoints.css")) {
    throw new TokenCssError(
      "tokens/index.css does not import generated/breakpoints.css. The token pipeline is disconnected.",
    );
  }
}

export function readFoundationCss(path: string): string {
  return readFileSync(path, "utf8");
}
