import { registerExtension } from "./registry";

registerExtension({
  id: "ventureos.shell",
  name: "VentureOS Shell",
  nav: [
    {
      id: "dashboard",
      label: "Situation Room",
      href: "/dashboard",
      section: "operate",
      icon: "layout-dashboard",
    },
    {
      id: "ventures",
      label: "Ventures",
      href: "/ventures",
      section: "operate",
      icon: "building-2",
    },
    {
      id: "agents",
      label: "Executive Office",
      href: "/agents",
      section: "intelligence",
      icon: "bot",
    },
    {
      id: "brain",
      label: "Brain",
      href: "/brain",
      section: "intelligence",
      icon: "brain",
    },
    {
      id: "engineering",
      label: "Engineering HQ",
      href: "/engineering",
      section: "system",
      icon: "drafting-compass",
    },
    {
      id: "settings",
      label: "Settings",
      href: "/settings",
      section: "system",
      icon: "settings",
    },
  ],
  commands: [
    {
      id: "nav.dashboard",
      title: "Go to Situation Room",
      group: "navigation",
      href: "/dashboard",
      keywords: ["home", "os", "dashboard", "briefing"],
    },
    {
      id: "nav.ventures",
      title: "Go to Ventures",
      group: "navigation",
      href: "/ventures",
      keywords: ["companies", "workspace", "hq"],
    },
    {
      id: "nav.agents",
      title: "Go to Executive Office",
      group: "ai",
      href: "/agents",
      keywords: ["runtime", "tools", "agents", "leadership", "office"],
    },
    {
      id: "nav.brain",
      title: "Go to Brain",
      group: "navigation",
      href: "/brain",
      keywords: ["knowledge", "constitution", "library", "intelligence"],
    },
    {
      id: "nav.brain.library",
      title: "Go to Knowledge Library",
      group: "navigation",
      href: "/brain/library",
      keywords: ["brain", "objects", "catalogue"],
    },
    {
      id: "nav.brain.decisions",
      title: "Go to Decision Register",
      group: "navigation",
      href: "/brain/decisions",
      keywords: ["brain", "adr", "rulings"],
    },
    {
      id: "nav.brain.search",
      title: "Search Brain",
      group: "navigation",
      href: "/brain/search",
      keywords: ["brain", "find", "knowledge"],
    },
    {
      id: "nav.engineering",
      title: "Go to Engineering HQ",
      group: "navigation",
      href: "/engineering",
      keywords: ["engineering", "hq", "sprints", "records", "constitution"],
    },
    {
      id: "nav.engineering.sprints",
      title: "Go to Sprint Centre",
      group: "navigation",
      href: "/engineering/sprints",
      keywords: ["engineering", "timeline", "vs"],
    },
    {
      id: "nav.settings",
      title: "Go to Settings",
      group: "system",
      href: "/settings",
    },
    {
      id: "ai.ask",
      title: "Ask VentureOS",
      group: "ai",
      action: "palette.ai",
      keywords: ["chat", "prompt", "agent"],
    },
    {
      id: "system.palette",
      title: "Open command palette",
      group: "system",
      action: "palette.open",
      keywords: ["search", "jump"],
    },
    {
      id: "system.notifications",
      title: "Open notifications",
      group: "system",
      action: "notifications.open",
    },
    {
      id: "system.theme.toggle",
      title: "Toggle theme",
      group: "system",
      action: "theme.toggle",
      keywords: ["dark", "light"],
    },
    {
      id: "system.theme.dark",
      title: "Use dark theme",
      group: "system",
      action: "theme.dark",
    },
    {
      id: "system.theme.light",
      title: "Use light theme",
      group: "system",
      action: "theme.light",
    },
    {
      id: "system.theme.system",
      title: "Use system theme",
      group: "system",
      action: "theme.system",
    },
  ],
});
