import { assertKnowledgeCatalogue, listDecisions, listGovernance } from "./knowledge-object";
import type {
  BrainActivity,
  BrainHealthMetric,
  KnowledgeObject,
  KnowledgeRelationship,
} from "./types";

function rel(...objectIds: string[]): KnowledgeRelationship[] {
  return objectIds.map((objectId) => ({ objectId }));
}

export const knowledgeObjects: KnowledgeObject[] = [
  {
    id: "creed",
    type: "Constitution",
    title: "VentureOS Creed",
    summary: "What the desk is for, who it serves, and what it refuses to become.",
    purpose: "Bind every surface to one operating system for companies.",
    why: "Without a creed, sprints invent a second product.",
    evidence: ["Foundation Library 01-FOUNDATION/VentureOS-Creed.md", "IDS-001 mission"],
    relationships: rel("principles", "adr-001"),
    history: [{ at: "2026-08-20", note: "Entered the Foundation Library as approved creed." }],
    aiContext:
      "VentureOS is the operating system for companies. Situation Room, Company HQ, and the Executive Office are one desk. Do not fork the OS.",
    reviewDate: "2026-11-20",
    lastReview: "2026-08-20",
    owner: "Founder",
    status: "Approved",
    version: "1.1.0",
    scopes: ["Platform"],
  },
  {
    id: "principles",
    type: "Constitution",
    title: "Twelve Founding Principles",
    summary: "The twelve non-negotiables of Foundation v1.1.",
    purpose: "Give every sprint a test it must still pass.",
    why: "Locked architecture fails when it is implied rather than named.",
    evidence: ["Foundation Library 01-FOUNDATION/Twelve-Founding-Principles.md"],
    relationships: rel("runtime", "ids", "adr-001", "adr-002", "adr-003", "adr-004"),
    history: [{ at: "2026-08-20", note: "Recorded from Foundation v1.0 ownership and IDS-001." }],
    aiContext:
      "One orchestrator. Capabilities govern; they do not dispatch. Definitions define products. IDS is presentation.",
    reviewDate: "2026-11-20",
    lastReview: "2026-08-20",
    owner: "Foundation",
    status: "Approved",
    version: "1.1.0",
    scopes: ["Platform"],
  },
  {
    id: "runtime",
    type: "Architecture",
    title: "Executive Intelligence Runtime",
    summary: "The only intelligence orchestrator. Persist is not a stage.",
    purpose: "Keep judgement in one call graph.",
    why: "A second entry would split the company document.",
    evidence: ["apps/web/src/core/runtime/README.md", "RUNTIME_PIPELINE"],
    relationships: rel("principles", "product-operating-system", "adr-001"),
    history: [{ at: "2026-08-20", note: "Locked with Foundation v1.1." }],
    aiContext:
      "Only runExecutiveIntelligenceRuntime orchestrates intelligence. Pages do not run the pipeline.",
    reviewDate: "2026-11-20",
    lastReview: "2026-08-20",
    owner: "Architecture",
    status: "Approved",
    version: "1.1.0",
    scopes: ["Platform"],
  },
  {
    id: "ids",
    type: "Standard",
    title: "IntelligenceOS Design System",
    summary: "Presentation constitution. Tokens before one-off colour.",
    purpose: "So every product on the OS reads as one desk.",
    why: "Brand must not become a second architecture.",
    evidence: ["IDS-001", "IDS-002", "packages/ids"],
    relationships: rel("eas-001", "adr-004", "adr-007"),
    history: [{ at: "2026-08-20", note: "Constitution locked; atmosphere specified, not painted." }],
    aiContext: "IDS is presentation. Do not import Runtime. Consume semantic roles. Two climates only.",
    reviewDate: "2026-11-20",
    lastReview: "2026-08-20",
    owner: "Design",
    status: "Approved",
    version: "1.1.0",
    scopes: ["Platform", "Qualora", "Calviora", "Farmora"],
  },
  {
    id: "engineering-standard",
    type: "Standard",
    title: "Engineering Standard",
    summary: "How code is written on the desk without restating Runtime law.",
    purpose: "Keep layers honest.",
    why: "Presentation that imports Runtime becomes a second orchestrator.",
    evidence: ["Foundation Library 04-ENGINEERING/Engineering-Standards.md"],
    relationships: rel("runtime", "adr-001"),
    history: [{ at: "2026-08-20", note: "Authored as the operating standard for Foundation v1.1." }],
    aiContext: "Do not import runExecutiveIntelligenceRuntime from screens. Fail fast at definition boundaries.",
    reviewDate: "2026-11-20",
    lastReview: "2026-08-20",
    owner: "Engineering",
    status: "Approved",
    version: "1.1.0",
    scopes: ["Platform"],
  },
  {
    id: "product-operating-system",
    type: "Playbook",
    title: "Product Operating System",
    summary: "One OS. Products run on it. There is no Product Registry.",
    purpose: "Tell founders and agents how a product meets the desk.",
    why: "A Product Registry would be a second source of truth.",
    evidence: ["Product Philosophy", "Venture Definitions"],
    relationships: rel("qualora-brief", "calviora-hold", "farmora-brief", "adr-003"),
    history: [{ at: "2026-08-20", note: "Recorded with Foundation Library DOC-001." }],
    aiContext:
      "The founder selects a Product. Products resolve through the Definition Registry. Theme never restores an excluded feature.",
    reviewDate: "2026-11-20",
    lastReview: "2026-08-20",
    owner: "Product",
    status: "Approved",
    version: "1.1.0",
    scopes: ["Platform", "Qualora", "Calviora", "Farmora"],
  },
  {
    id: "ai-constitution",
    type: "Policy",
    title: "AI Constitution",
    summary: "Ask is a command surface. It is not a chat Runtime.",
    purpose: "Keep agents inside the same law as the desk.",
    why: "A private agent pipeline would bypass judgement.",
    evidence: ["Interaction Constitution", "Runtime ownership"],
    relationships: rel("runtime", "adr-001"),
    history: [{ at: "2026-08-20", note: "Stated in IDS component philosophy and the Creed." }],
    aiContext:
      "Do not treat the command palette as an orchestrator. Do not invent embeddings in Foundation sprints.",
    reviewDate: "2027-02-20",
    lastReview: "2026-08-20",
    owner: "Foundation",
    status: "Specified",
    version: "0.1.0",
    scopes: ["Platform"],
  },
  {
    id: "security-standard",
    type: "Standard",
    title: "Security Standard",
    summary: "Sessions, reset tokens, and OAuth linking as they stand in Foundation v1.1.",
    purpose: "Name how the desk authenticates without a second identity Runtime.",
    why: "Identity lives in platform services. It does not import Runtime.",
    evidence: ["Auth module", "Password reset tokens hashed SHA-256"],
    relationships: rel("engineering-standard", "adr-001"),
    history: [{ at: "2026-08-20", note: "VS-011 authentication experience recorded." }],
    aiContext:
      "httpOnly session cookie. Reset tokens are hashed and single-use. Google accounts link after matching password sign-in.",
    reviewDate: "2026-11-20",
    lastReview: "2026-08-20",
    owner: "Engineering",
    status: "Living",
    version: "1.1.0",
    scopes: ["Platform"],
  },
  {
    id: "eas-001",
    type: "Blueprint",
    title: "Executive Atmosphere Architecture",
    summary: "Layer 2 headquarters recognition. Specified. Not painted.",
    purpose: "Separate climate from atmosphere without forking the OS.",
    why: "Accent overlay is not a headquarters.",
    evidence: ["EAS-001", "Assumption A-001"],
    relationships: rel("ids", "calviora-hold", "adr-007"),
    history: [{ at: "2026-08-20", note: "Published as design-only for Foundation v1.1." }],
    aiContext:
      "Do not implement atmosphere inside a climate sprint. Do not paint Calviora until identity is ratified.",
    reviewDate: "2027-02-20",
    lastReview: "2026-08-20",
    owner: "Design",
    status: "Specified",
    version: "1.1.0",
    scopes: ["Platform", "Qualora", "Calviora", "Farmora"],
  },
  {
    id: "qualora-brief",
    type: "Research",
    title: "Qualora on the desk",
    summary: "Quality and evidence operations. Full intelligence pack including briefing.",
    purpose: "Hold product truth without a Qualora application.",
    why: "Operators must recognise the same OS.",
    evidence: ["Definition Registry qualora@0.3.0"],
    relationships: rel("product-operating-system", "ids", "adr-003"),
    history: [{ at: "2026-08-20", note: "Indexed from the live definition catalogue." }],
    aiContext: "Qualora is incubating. Do not invent a private Runtime or a traffic-light overlay.",
    reviewDate: "2026-12-01",
    lastReview: "2026-08-20",
    owner: "Product",
    status: "Living",
    version: "0.3.0",
    scopes: ["Qualora"],
  },
  {
    id: "calviora-hold",
    type: "Research",
    title: "Calviora identity hold",
    summary: "Live definition is livestock cadence. EAS-001 proposes healthcare operations.",
    purpose: "Stop painting until product and IDS name the same headquarters.",
    why: "Theme must not decide product identity.",
    evidence: ["Assumption A-001", "Founder Decision FD-006"],
    relationships: rel("eas-001", "fd-006"),
    history: [{ at: "2026-08-20", note: "Conflict recorded; not resolved." }],
    aiContext: "Do not paint Calviora. Do not costume a morning briefing the definition excludes.",
    reviewDate: "2026-10-01",
    lastReview: "2026-08-20",
    owner: "Product",
    status: "Concept",
    version: "0.1.0",
    scopes: ["Calviora"],
  },
  {
    id: "roadmap-v11",
    type: "Roadmap",
    title: "Foundation v1.1 remainder",
    summary: "Atmosphere, accessibility Layer 3, production mail, Calviora ratification.",
    purpose: "Keep specified work from becoming accidental architecture.",
    why: "A silent backlog becomes a second creed.",
    evidence: ["Roadmap Register RM-001 to RM-007"],
    relationships: rel("eas-001", "ai-constitution", "adr-007"),
    history: [{ at: "2026-08-20", note: "Opened with the Foundation Library." }],
    aiContext: "Do not add a third climate or a Product Registry to this roadmap.",
    reviewDate: "2026-11-20",
    lastReview: "2026-08-20",
    owner: "Product",
    status: "Living",
    version: "1.1.0",
    scopes: ["Platform"],
  },
  {
    id: "farmora-brief",
    type: "Research",
    title: "Farmora on the desk",
    summary: "Agricultural operations. Indexed as a product on the OS, not a private application.",
    purpose: "Hold product truth without a Farmora fork.",
    why: "Operators must recognise the same desk across ventures.",
    evidence: ["Definition Registry farmora", "Product Operating System"],
    relationships: rel("product-operating-system", "ids", "adr-003"),
    history: [{ at: "2026-08-20", note: "Indexed from the live definition catalogue." }],
    aiContext: "Farmora is a product on VentureOS. Do not invent a private Runtime.",
    reviewDate: "2026-12-01",
    lastReview: "2026-08-20",
    owner: "Product",
    status: "Living",
    version: "0.1.0",
    scopes: ["Farmora"],
  },
  {
    id: "adr-001",
    type: "Decision",
    title: "The Executive Intelligence Runtime is the only orchestrator",
    summary: "ADR-001. One company document cannot have two pipelines.",
    purpose: "Keep judgement in one call graph.",
    why: "Per-page intelligence or capability dispatch would split the company document.",
    evidence: ["core/runtime/README.md — RUNTIME_PIPELINE"],
    relationships: rel("runtime", "principles"),
    history: [{ at: "2026-08-20", note: "Accepted as Foundation law." }],
    aiContext: "Only runExecutiveIntelligenceRuntime orchestrates intelligence.",
    reviewDate: "2027-02-20",
    lastReview: "2026-08-20",
    owner: "Architecture",
    status: "Approved",
    version: "1.1.0",
    scopes: ["Platform"],
    impact: "Platform",
    alternatives: ["Per-page intelligence", "Plugin dispatch through capabilities"],
    issuedAt: "2026-08-20",
  },
  {
    id: "adr-002",
    type: "Decision",
    title: "The Capability Registry governs; it does not dispatch",
    summary: "ADR-002. Capabilities are building blocks, not a second runtime.",
    purpose: "Keep the registry from becoming an orchestrator.",
    why: "Dynamic module loading would hide the call graph.",
    evidence: ["core/capability/README.md"],
    relationships: rel("principles", "runtime"),
    history: [{ at: "2026-08-20", note: "Accepted as Foundation law." }],
    aiContext: "Capabilities govern; they do not dispatch or persist.",
    reviewDate: "2027-02-20",
    lastReview: "2026-08-20",
    owner: "Architecture",
    status: "Approved",
    version: "1.1.0",
    scopes: ["Platform"],
    impact: "Platform",
    alternatives: ["Dynamic module loading", "Capability-to-route map"],
    issuedAt: "2026-08-20",
  },
  {
    id: "adr-003",
    type: "Decision",
    title: "The Definition Registry is the only product-definition system",
    summary: "ADR-003. A Product Registry would fork truth.",
    purpose: "Keep product identity in one catalogue.",
    why: "A second registry would let theme or launch invent a product.",
    evidence: ["core/venture-definition/README.md"],
    relationships: rel("product-operating-system", "qualora-brief"),
    history: [{ at: "2026-08-20", note: "Accepted as Foundation law." }],
    aiContext: "Do not add a Product Registry beside definitions.",
    reviewDate: "2027-02-20",
    lastReview: "2026-08-20",
    owner: "Product",
    status: "Approved",
    version: "1.1.0",
    scopes: ["Platform", "Qualora", "Calviora", "Farmora"],
    impact: "Product",
    alternatives: ["Product Registry beside definitions", "Per-venture code forks"],
    issuedAt: "2026-08-20",
  },
  {
    id: "adr-004",
    type: "Decision",
    title: "IDS is presentation only",
    summary: "ADR-004. Clothing the OS must not become the OS.",
    purpose: "Keep tokens from gating capabilities.",
    why: "Theme-driven flags would restore excluded features by costume.",
    evidence: ["IDS-001 constitutional rules"],
    relationships: rel("ids", "principles"),
    history: [{ at: "2026-08-20", note: "Accepted as Foundation law." }],
    aiContext: "IDS is presentation. Screens consume semantic roles.",
    reviewDate: "2027-02-20",
    lastReview: "2026-08-20",
    owner: "Design",
    status: "Approved",
    version: "1.1.0",
    scopes: ["Platform"],
    impact: "Presentation",
    alternatives: ["Theme-driven capability flags", "Per-product type scales"],
    issuedAt: "2026-08-20",
  },
  {
    id: "adr-007",
    type: "Decision",
    title: "Two climates only; atmosphere is specified separately",
    summary: "ADR-007. A third climate would be costume, not judgement.",
    purpose: "Keep Executive Light and Executive Dark as the only climates.",
    why: "Brand as a next-themes theme would fork the desk.",
    evidence: ["EAS-001", "ThemeProvider attribute=class"],
    relationships: rel("eas-001", "ids"),
    history: [{ at: "2026-08-20", note: "Accepted as Foundation law." }],
    aiContext: "Do not add a midnight climate. Atmosphere is specified, not painted.",
    reviewDate: "2027-02-20",
    lastReview: "2026-08-20",
    owner: "Design",
    status: "Approved",
    version: "1.1.0",
    scopes: ["Platform"],
    impact: "Presentation",
    alternatives: ["Midnight climate", "Brand as a next-themes theme"],
    issuedAt: "2026-08-20",
  },
  {
    id: "fd-006",
    type: "Decision",
    title: "Calviora identity is not ratified",
    summary: "Founder Decision FD-006. Livestock cadence and healthcare headquarters cannot both be painted.",
    purpose: "Keep theme from deciding product identity before the founder does.",
    why: "EAS-001 and the live Calviora definition currently name different companies.",
    evidence: ["Founder Decision FD-006", "Assumption A-001", "live definition calviora@0.1.0"],
    relationships: rel("calviora-hold", "eas-001"),
    history: [{ at: "2026-08-20", note: "Opened as an unresolved founder decision." }],
    aiContext: "Do not paint Calviora. Do not resolve FD-006 in a presentation sprint.",
    reviewDate: "2026-10-01",
    lastReview: "2026-08-20",
    owner: "Founder",
    status: "Concept",
    version: "0.1.0",
    scopes: ["Calviora"],
    impact: "Product",
    alternatives: ["Amend IDS to healthcare", "Keep livestock and reject EAS-001 Calviora"],
    issuedAt: "2026-08-20",
  },
];

assertKnowledgeCatalogue(knowledgeObjects);

export const decisions = listDecisions(knowledgeObjects);
export const governanceInstruments = listGovernance(knowledgeObjects);

export const recentActivity: BrainActivity[] = [
  {
    id: "act-1",
    at: "2026-08-20",
    note: "Foundation Library opened as the reading system for v1.1.",
    href: "/brain/library/creed",
  },
  {
    id: "act-2",
    at: "2026-08-20",
    note: "Authentication experience recorded against the Security Standard.",
    href: "/brain/library/security-standard",
  },
  {
    id: "act-3",
    at: "2026-08-20",
    note: "Calviora identity held as an open founder decision.",
    href: "/brain/library/fd-006",
  },
  {
    id: "act-4",
    at: "2026-08-21",
    note: "Geist variables moved to html so IDS type tokens resolve.",
    href: "/brain/library/ids",
  },
];

export const brainHealth: BrainHealthMetric[] = [
  {
    id: "coverage",
    title: "Knowledge coverage",
    value: "19 objects",
    judgement: "Core law is present. Research beyond the three products is thin.",
    band: "healthy",
  },
  {
    id: "freshness",
    title: "Documentation freshness",
    value: "All reviewed 2026-08-20",
    judgement: "The library is new. Freshness will matter after the next quarter.",
    band: "healthy",
  },
  {
    id: "overdue",
    title: "Review overdue",
    value: "0",
    judgement: "No object has passed its review date.",
    band: "healthy",
  },
  {
    id: "relationships",
    title: "Broken relationships",
    value: "0",
    judgement: "Named relationships resolve to Knowledge Object ids.",
    band: "healthy",
  },
  {
    id: "conflicts",
    title: "Conflicting standards",
    value: "1 open",
    judgement: "Calviora livestock versus healthcare headquarters remains unresolved.",
    band: "watch",
  },
  {
    id: "traceability",
    title: "Decision traceability",
    value: "6 of 6",
    judgement: "Every decision is a Knowledge Object, not a parallel record.",
    band: "healthy",
  },
  {
    id: "ai-context",
    title: "AI context coverage",
    value: "19 of 19",
    judgement: "Each object carries a short context the desk can later pass to an agent.",
    band: "healthy",
  },
];

export const suggestedSearches = [
  "one orchestrator",
  "Calviora identity",
  "IDS presentation",
  "Definition Registry",
];

export const recentSearches = ["Runtime pipeline", "password reset", "atmosphere"];
