import { CAPABILITY_CONTRACTS } from "./contracts";
import { createCapabilityManifest } from "./model";
import { createCapabilityRegistry } from "./registry";
import type { CapabilityManifest } from "./types";

const C = CAPABILITY_CONTRACTS;

export const platformCapabilityCatalog: CapabilityManifest[] = [
  createCapabilityManifest({
    id: "platform.capability-framework",
    name: "Shared Capability Framework",
    classification: "Platform",
    purpose:
      "Registry, contract and governance for reusable VentureOS capabilities. Not an orchestrator.",
    owner: "platform",
    version: "0.3.0",
    maturity: "alpha",
    lifecycle: "shared",
    dependencies: [],
    provides: [C.capabilityRegistry],
    requires: [],
    guarantees: [
      "Ventures resolve shared capabilities only through the registry.",
      "Duplicate ids, missing dependencies and cycles fail at registry creation.",
    ],
    limitations: [
      "Does not persist, load plugins, or dispatch implementations.",
    ],
  }),
  createCapabilityManifest({
    id: "platform.identity",
    name: "Identity",
    classification: "Platform",
    purpose: "Founder and company identity records used across intelligence documents.",
    owner: "platform",
    version: "1.0.0",
    maturity: "ga",
    lifecycle: "stable",
    dependencies: [],
    provides: [C.founderIdentity],
    requires: [],
    guarantees: ["Identity fields are plain facts on the Venture Intelligence Core."],
    limitations: ["Does not authenticate users."],
  }),
  createCapabilityManifest({
    id: "data.venture-genome",
    name: "Venture Genome",
    classification: "Data",
    purpose: "Thesis, category, stage, goal and motion for a company.",
    owner: "platform",
    version: "1.0.0",
    maturity: "ga",
    lifecycle: "stable",
    dependencies: [],
    provides: [C.ventureGenome],
    requires: [],
    guarantees: ["Genome is venture-scoped fact, not a recommendation."],
    limitations: ["Does not infer genome; founding supplies it."],
  }),
  createCapabilityManifest({
    id: "intelligence.venture-core",
    name: "Venture Intelligence Core",
    classification: "Intelligence",
    purpose: "Document of record for founder, portfolio, ventures and derived intelligence.",
    owner: "intelligence",
    version: "1.0.0",
    maturity: "ga",
    lifecycle: "stable",
    dependencies: ["platform.identity"],
    provides: [C.ventureIntelligenceCore],
    requires: [C.founderIdentity],
    guarantees: ["VIC remains the single intelligence document of record."],
    limitations: ["Does not orchestrate engines."],
  }),
  createCapabilityManifest({
    id: "intelligence.policy-engine",
    name: "Executive Policy Engine",
    classification: "Governance",
    purpose: "Evaluate executive policies against VIC facts and emit findings.",
    owner: "intelligence",
    version: "1.0.0",
    maturity: "ga",
    lifecycle: "stable",
    dependencies: ["intelligence.venture-core"],
    provides: [C.policyEvaluation],
    requires: [C.ventureIntelligenceCore],
    guarantees: ["Policy evaluation runs only inside the Executive Intelligence Runtime."],
    limitations: ["Does not persist findings itself."],
  }),
  createCapabilityManifest({
    id: "intelligence.recommendation-engine",
    name: "Recommendation Engine",
    classification: "Intelligence",
    purpose: "Turn policy findings into ranked, evidence-backed recommendations.",
    owner: "intelligence",
    version: "1.0.0",
    maturity: "ga",
    lifecycle: "stable",
    dependencies: ["intelligence.policy-engine", "intelligence.venture-core"],
    provides: [C.recommendationGeneration],
    requires: [C.policyEvaluation, C.ventureIntelligenceCore],
    guarantees: ["Recommendations are derived from findings, not page copy."],
    limitations: ["Does not record founder rulings."],
  }),
  createCapabilityManifest({
    id: "intelligence.executive-memory",
    name: "Executive Memory",
    classification: "Intelligence",
    purpose: "Durable recall of founding and founder calls for briefing and desks.",
    owner: "intelligence",
    version: "1.0.0",
    maturity: "ga",
    lifecycle: "stable",
    dependencies: ["intelligence.venture-core"],
    provides: [C.executiveMemory],
    requires: [C.ventureIntelligenceCore],
    guarantees: ["Memory records are idempotent by identity."],
    limitations: ["Does not invent narrative beyond recorded facts."],
  }),
  createCapabilityManifest({
    id: "intelligence.operating-health",
    name: "Operating Health",
    classification: "Intelligence",
    purpose: "Company and portfolio health bands, posture and watches.",
    owner: "intelligence",
    version: "1.0.0",
    maturity: "ga",
    lifecycle: "stable",
    dependencies: ["intelligence.venture-core"],
    provides: [C.operatingHealth],
    requires: [C.ventureIntelligenceCore],
    guarantees: ["Health refresh is deterministic for the same VIC facts."],
    limitations: ["Scoring rules are Runtime effects, not a separate orchestrator."],
  }),
  createCapabilityManifest({
    id: "intelligence.company-story",
    name: "Company Story",
    classification: "Intelligence",
    purpose: "Chapter, excerpt and tension for the company narrative.",
    owner: "intelligence",
    version: "1.0.0",
    maturity: "ga",
    lifecycle: "stable",
    dependencies: ["intelligence.venture-core"],
    provides: [C.companyStory],
    requires: [C.ventureIntelligenceCore],
    guarantees: ["Story mutates only through Runtime events."],
    limitations: ["Not a publishing surface."],
  }),
  createCapabilityManifest({
    id: "intelligence.knowledge-graph",
    name: "Knowledge Graph",
    classification: "Intelligence",
    purpose: "Venture nodes and ownership edges on the intelligence document.",
    owner: "intelligence",
    version: "1.0.0",
    maturity: "ga",
    lifecycle: "stable",
    dependencies: ["intelligence.venture-core", "platform.identity"],
    provides: [C.knowledgeGraph],
    requires: [C.ventureIntelligenceCore, C.founderIdentity],
    guarantees: ["Graph refresh is idempotent for the same venture and founder."],
    limitations: ["Not a general-purpose graph database."],
  }),
  createCapabilityManifest({
    id: "intelligence.decision-engine",
    name: "Decision Engine",
    classification: "Governance",
    purpose: "Upcoming and resolved founder decisions attached to a venture.",
    owner: "intelligence",
    version: "1.0.0",
    maturity: "ga",
    lifecycle: "stable",
    dependencies: ["intelligence.venture-core"],
    provides: [C.decisionRecord],
    requires: [C.ventureIntelligenceCore],
    guarantees: ["Resolved decisions keep their identity on replay."],
    limitations: ["Does not run the intelligence pipeline."],
  }),
  createCapabilityManifest({
    id: "intelligence.risk",
    name: "Risk Intelligence",
    classification: "Intelligence",
    purpose: "Risk headline and signals used by briefing and policy evidence.",
    owner: "intelligence",
    version: "1.0.0",
    maturity: "ga",
    lifecycle: "stable",
    dependencies: ["intelligence.venture-core"],
    provides: [C.riskIntelligence],
    requires: [C.ventureIntelligenceCore],
    guarantees: ["Primary risk is the first registered signal."],
    limitations: ["Does not score portfolio health."],
  }),
  createCapabilityManifest({
    id: "intelligence.mission",
    name: "Mission Engine",
    classification: "Intelligence",
    purpose: "Today's constraint and sprint objective for a company.",
    owner: "intelligence",
    version: "1.0.0",
    maturity: "ga",
    lifecycle: "stable",
    dependencies: ["intelligence.venture-core"],
    provides: [C.missionConstraint],
    requires: [C.ventureIntelligenceCore],
    guarantees: ["Mission facts live on VIC; Situation Room may overlay recommendations."],
    limitations: ["Does not rank portfolio attention."],
  }),
  createCapabilityManifest({
    id: "intelligence.briefing",
    name: "Executive Briefing",
    classification: "Intelligence",
    purpose: "Assemble one morning briefing from VIC, recommendations, health, story and risk.",
    owner: "intelligence",
    version: "0.3.0",
    maturity: "beta",
    lifecycle: "shared",
    dependencies: [
      "intelligence.recommendation-engine",
      "intelligence.operating-health",
      "intelligence.company-story",
      "intelligence.risk",
      "intelligence.executive-memory",
    ],
    provides: [C.executiveBriefing],
    requires: [
      C.recommendationGeneration,
      C.operatingHealth,
      C.companyStory,
      C.riskIntelligence,
      C.executiveMemory,
    ],
    guarantees: [
      "Headline, narrative and implications are assembled from intelligence objects.",
    ],
    limitations: ["Does not introduce Situation Room sections."],
  }),
  createCapabilityManifest({
    id: "intelligence.runtime",
    name: "Executive Intelligence Runtime",
    classification: "Intelligence",
    purpose: "Sole intelligence orchestrator. Applies events, runs engines, returns VIC.",
    owner: "intelligence",
    version: "1.0.0",
    maturity: "ga",
    lifecycle: "stable",
    dependencies: [
      "intelligence.venture-core",
      "intelligence.policy-engine",
      "intelligence.recommendation-engine",
      "intelligence.operating-health",
      "intelligence.knowledge-graph",
      "intelligence.executive-memory",
      "intelligence.company-story",
      "intelligence.briefing",
      "platform.capability-framework",
    ],
    provides: [C.orchestration],
    requires: [
      C.ventureIntelligenceCore,
      C.policyEvaluation,
      C.recommendationGeneration,
      C.operatingHealth,
      C.knowledgeGraph,
      C.capabilityRegistry,
    ],
    guarantees: [
      "The only permitted orchestration path for intelligence mutations.",
      "Resolves required capabilities through the registry without dispatching them.",
    ],
    limitations: [
      "Does not load capabilities dynamically.",
      "Does not persist; the intelligence service writes snapshots after mutations.",
    ],
  }),
  createCapabilityManifest({
    id: "governance.executive-office",
    name: "Executive Office",
    classification: "Governance",
    purpose: "Seated desks, remit and operating status for the leadership floor.",
    owner: "governance",
    version: "1.0.0",
    maturity: "ga",
    lifecycle: "stable",
    dependencies: ["intelligence.venture-core"],
    provides: [C.executiveOffice],
    requires: [C.ventureIntelligenceCore],
    guarantees: ["Office composition is fact on VIC."],
    limitations: ["Does not execute desk work."],
  }),
  createCapabilityManifest({
    id: "governance.founder-decision",
    name: "Founder Decision Recording",
    classification: "Governance",
    purpose: "Record a founder ruling as a Runtime event.",
    owner: "governance",
    version: "1.0.0",
    maturity: "ga",
    lifecycle: "stable",
    dependencies: ["intelligence.runtime", "intelligence.decision-engine"],
    provides: [C.decisionRecord],
    requires: [C.orchestration, C.decisionRecord],
    guarantees: ["Founder decisions enter VIC only through the Runtime."],
    limitations: ["UI remains presentational."],
  }),
  createCapabilityManifest({
    id: "assurance.evidence-assessment",
    name: "Assurance Evidence Assessment",
    classification: "Intelligence",
    purpose:
      "Record a bounded, AI-generated, unconfirmed evidence-gap assessment against one supplied assurance requirement. Does not determine regulatory truth.",
    owner: "intelligence",
    version: "1.0.0",
    maturity: "experimental",
    lifecycle: "internal",
    dependencies: [],
    provides: [C.assuranceEvidenceAssessment],
    requires: [],
    guarantees: [
      "Registration names the capability only; it does not grant authority or dispatch an implementation.",
      "A durable assessment, if created, is proposed and unconfirmed. It is not a compliance determination.",
    ],
    limitations: [
      "Does not confirm, dismiss, close, or delete assessments.",
      "Does not retrieve regulations, browse the web, or declare CQC outcomes.",
      "Verification of execution state is not verification of regulatory judgement.",
    ],
  }),
];

export const platformCapabilityRegistry = createCapabilityRegistry(
  platformCapabilityCatalog,
);
