export type LayoutPrimitiveRecord = {
  name: string;
  purpose: string;
  responsibilities: string;
  allowedChildren: string;
  forbiddenChildren: string;
  responsive: string;
  accessibility: string;
  tokens: readonly string[];
  example: string;
  migration: string;
};

export const LAYOUT_PRIMITIVES: readonly LayoutPrimitiveRecord[] = [
  {
    name: "Workspace",
    purpose: "Root climate canvas for a VentureOS session.",
    responsibilities: "Fill the viewport height. Apply climate background. Host skip, rail, stage, and command.",
    allowedChildren: "SkipLink, NavigationRail, SplitView, Stage, CommandRegion",
    forbiddenChildren: "Runtime output, forms as the root, product grids",
    responsive: "Row at all breakpoints. NavigationRail handles collapse.",
    accessibility: "Does not own the main landmark. SkipLink is a sibling.",
    tokens: ["--ids-foundation-color-background"],
    example: "Workspace > SkipLink + NavigationRail + Stage",
    migration: "Replaces ExecutiveFrame for the OS shell. Authentication still uses ExecutiveFrame as an alias.",
  },
  {
    name: "NavigationRail",
    purpose: "Primary wayfinding column for a workspace.",
    responsibilities: "Fixed width. Host brand, sections, and items. Overlay on small viewports when open.",
    allowedChildren: "NavigationBrand, NavigationMenu",
    forbiddenChildren: "WorkspaceCanvas, intelligence cards, forms",
    responsive: "Hidden below large unless open. Overlay dismisses on small viewports.",
    accessibility: "id=primary-navigation. Overlay button labelled Close navigation.",
    tokens: [
      "--ids-foundation-layout-sidebar-sm",
      "--ids-foundation-layout-sidebar-md",
      "--ids-foundation-z-sidebar",
      "--ids-foundation-z-dialog",
    ],
    example: "NavigationRail open onDismiss > NavigationBrand + NavigationMenu",
    migration: "Replaces the shell aside. Not the authentication BrandRail.",
  },
  {
    name: "WorkspaceCanvas",
    purpose: "Bounded operating canvas inside the workspace main landmark.",
    responsibilities: "Centre a measure.xl column. Apply screen inset. Stack page regions.",
    allowedChildren: "HeaderRule, Document, Dashboard, Flow, Grid, StatusRegion",
    forbiddenChildren: "NavigationRail, CommandRegion, SkipLink",
    responsive: "Full width until measure.xl. vos-screen padding grows at large.",
    accessibility: "Lives inside WorkspaceMain. Does not create a second main.",
    tokens: ["--ids-foundation-layout-measure-xl", "--ids-foundation-space-8"],
    example: "WorkspaceMain > WorkspaceCanvas > HeaderRule + Dashboard",
    migration: "Replaces page-frame max-w-[72rem] canvas.",
  },
  {
    name: "Dashboard",
    purpose: "Primary operating body of a workspace page.",
    responsibilities: "Vertical flow of judgements, grids, and panels.",
    allowedChildren: "Grid, Flow, Stack, ReadingRegion, Inspector, SplitView",
    forbiddenChildren: "NavigationRail, Toolbar, CommandRegion",
    responsive: "Column at all breakpoints. Children own their grids.",
    accessibility: "No landmark of its own.",
    tokens: ["--ids-foundation-space-8"],
    example: "Dashboard > Grid variant=executive",
    migration: "Replaces the inner gap-8 column of PageFrame.",
  },
  {
    name: "Document",
    purpose: "Title block for a workspace or authentication page.",
    responsibilities: "Kicker, heading, optional lede, description, meta.",
    allowedChildren: "None. Text props only.",
    forbiddenChildren: "Forms, grids, navigation",
    responsive: "Stacks. Meta sits beside kicker when clustered.",
    accessibility: "One h1. Colour is not the heading.",
    tokens: ["--ids-foundation-space-2"],
    example: "Document kicker title description",
    migration: "Workspace header uses HeaderRule + ids-display. Auth keeps ExecutiveDocument.",
  },
  {
    name: "ReadingRegion",
    purpose: "Bounded reading measure for prose and title copy.",
    responsibilities: "Cap width to a measure token. Do not centre unless asked by a parent.",
    allowedChildren: "Type roles, Stack, lists",
    forbiddenChildren: "NavigationRail, Grid analytics, CommandRegion",
    responsive: "Width cap only. Parent owns padding.",
    accessibility: "Improves line length. Not a landmark.",
    tokens: [
      "--ids-foundation-layout-measure-sm",
      "--ids-foundation-layout-measure-md",
      "--ids-foundation-layout-measure-lg",
      "--ids-foundation-layout-measure-xl",
    ],
    example: "ReadingRegion size=lg > ids-body",
    migration: "Replaces max-w-[42rem] prose and max-w-lg empty copy.",
  },
  {
    name: "Inspector",
    purpose: "Secondary column for correspondence, filters, or supporting judgement.",
    responsibilities: "Sidebar.lg width from large breakpoint. Optional stickiness.",
    allowedChildren: "Stack, Panel, type roles",
    forbiddenChildren: "NavigationRail, WorkspaceCanvas, CommandRegion",
    responsive: "Full width below large. sidebar.lg from large.",
    accessibility: "aside. Sticky does not trap focus.",
    tokens: ["--ids-foundation-layout-sidebar-lg", "--ids-foundation-space-6"],
    example: "SplitView > Flow + Inspector sticky",
    migration: "Replaces 17.5rem office and 16rem brain supporting columns.",
  },
  {
    name: "Panel",
    purpose: "Fixed-width overlay or supporting box.",
    responsibilities: "Apply a panel size token. No surface chrome of its own.",
    allowedChildren: "Stack, EmptyCopy, lists",
    forbiddenChildren: "Workspace, NavigationRail",
    responsive: "max-w-full so small viewports can shrink.",
    accessibility: "Not a dialog. Popover or CommandRegion owns modality.",
    tokens: [
      "--ids-foundation-layout-panel-sm",
      "--ids-foundation-layout-panel-md",
      "--ids-foundation-layout-panel-lg",
    ],
    example: "Panel size=md > popover body",
    migration: "Replaces w-72 and w-80 chrome widths.",
  },
  {
    name: "Toolbar",
    purpose: "Workspace chrome above the main landmark.",
    responsibilities: "Fixed toolbar height. Horizontal cluster of wayfinding controls.",
    allowedChildren: "Reveal, Grow, Trailing, switchers, icon buttons",
    forbiddenChildren: "WorkspaceCanvas, Grid, forms as page documents",
    responsive: "Padding and gap increase at small. Children use Reveal.",
    accessibility: "role=banner. Does not replace SkipLink.",
    tokens: [
      "--ids-foundation-layout-toolbar",
      "--ids-foundation-space-2",
      "--ids-foundation-space-3",
      "--ids-foundation-space-4",
    ],
    example: "Toolbar > Reveal + Grow + Trailing",
    migration: "Replaces TopNav header layout.",
  },
  {
    name: "StatusRegion",
    purpose: "Page footer status and secondary acts.",
    responsibilities: "Hairline above. Push to the end of the canvas when the parent is a column.",
    allowedChildren: "Type roles, Cluster, links",
    forbiddenChildren: "NavigationRail, CommandRegion",
    responsive: "Full canvas width.",
    accessibility: "footer landmark inside the page, not the OS chrome.",
    tokens: ["--ids-foundation-space-6"],
    example: "WorkspaceCanvas > Dashboard + StatusRegion",
    migration: "Replaces PageFrame footer.",
  },
  {
    name: "CommandRegion",
    purpose: "Modal command surface.",
    responsibilities: "Overlay, dismiss control, bounded dialog measure.",
    allowedChildren: "Command field, Stack, EmptyCopy, lists",
    forbiddenChildren: "NavigationRail, WorkspaceCanvas, Runtime calls",
    responsive: "measure.md dialog. Overlay inset from space-4.",
    accessibility: "role=dialog aria-modal. Dismiss labelled. Ask is not a chat Runtime.",
    tokens: [
      "--ids-foundation-layout-command-offset",
      "--ids-foundation-layout-measure-md",
      "--ids-foundation-z-dialog",
      "--ids-foundation-space-4",
    ],
    example: "CommandRegion label onDismiss > input + list",
    migration: "Replaces command palette overlay positioning.",
  },
  {
    name: "Grid",
    purpose: "Workspace grid of peer regions.",
    responsibilities: "executive = two columns from large. analytics = two from medium, four from extra-large.",
    allowedChildren: "Panel contents, cards, Stack",
    forbiddenChildren: "NavigationRail, CommandRegion, SkipLink",
    responsive: "Single column first. Token templates from the named breakpoints.",
    accessibility: "DOM order is reading order.",
    tokens: [
      "--ids-foundation-layout-grid-executive",
      "--ids-foundation-layout-grid-analytics",
      "--ids-foundation-space-4",
    ],
    example: "Grid variant=analytics > metric regions",
    migration: "Replaces lg:grid-cols-2 and xl:grid-cols-4 product grids.",
  },
  {
    name: "Flow",
    purpose: "Vertical sequence of page regions.",
    responsibilities: "Section gap. Grow inside the canvas.",
    allowedChildren: "Grid, Stack, SplitView, ReadingRegion, Inspector",
    forbiddenChildren: "Toolbar, CommandRegion",
    responsive: "Column at all breakpoints.",
    accessibility: "No landmark.",
    tokens: ["--ids-foundation-space-8"],
    example: "Flow > Grid + ReadingRegion",
    migration: "Shared with Dashboard. Prefer Dashboard as the page body, Flow inside SplitView.",
  },
  {
    name: "Stack",
    purpose: "Vertical rhythm.",
    responsibilities: "tight, compact, form, or section gap. No width opinion.",
    allowedChildren: "Type, fields, clusters, nested stacks",
    forbiddenChildren: "Workspace, NavigationRail as a child of a form stack",
    responsive: "Column at all breakpoints.",
    accessibility: "No landmark.",
    tokens: [
      "--ids-foundation-space-2",
      "--ids-foundation-space-3",
      "--ids-foundation-space-6",
      "--ids-foundation-space-8",
    ],
    example: "Stack gap=section > Document + Form",
    migration: "ExecutiveStack alias. compact added for supporting chrome.",
  },
  {
    name: "Cluster",
    purpose: "Horizontal grouping of peer acts.",
    responsibilities: "Wrap by default. Space between by default. Auth paired actions stay on this primitive.",
    allowedChildren: "Buttons, links, captions, Fit",
    forbiddenChildren: "Grid, NavigationRail",
    responsive: "Wraps. Parent may set wrap=false for chrome.",
    accessibility: "Not a toolbar unless the parent is Toolbar.",
    tokens: ["--ids-foundation-space-2", "--ids-foundation-space-3"],
    example: "Cluster > secondary link + primary button",
    migration: "ExecutiveCluster alias.",
  },
  {
    name: "SplitView",
    purpose: "Group two peer regions without a box.",
    responsibilities: "Fragment. Children supply their own boxes.",
    allowedChildren: "BrandRail+Stage, Flow+Inspector, NavigationRail+Stage",
    forbiddenChildren: "Unrelated third application layers",
    responsive: "Children own breakpoints.",
    accessibility: "No node, no landmark.",
    tokens: [],
    example: "SplitView > BrandRail + Stage",
    migration: "ExecutiveSplit alias.",
  },
  {
    name: "SkipLink",
    purpose: "Skip to the workspace main landmark.",
    responsibilities: "Visually hidden until focus. Targets #main-content.",
    allowedChildren: "None.",
    forbiddenChildren: "Any.",
    responsive: "Fixed to the viewport.",
    accessibility: "First focusable control in Workspace. Required.",
    tokens: ["--ids-foundation-layout-skip-shift", "--ids-foundation-z-skip"],
    example: "Workspace > SkipLink",
    migration: "Moved out of OsShell class strings.",
  },
  {
    name: "Stage",
    purpose: "Growing column beside a rail.",
    responsibilities: "flex-1 min-size zero. Host toolbar, banner, or main.",
    allowedChildren: "Toolbar, Banner, WorkspaceMain, Main",
    forbiddenChildren: "SkipLink, CommandRegion overlay as a layout child of the column is allowed at Workspace level only",
    responsive: "Fills remaining row width.",
    accessibility: "No landmark.",
    tokens: [],
    example: "Stage > Toolbar + WorkspaceMain",
    migration: "ExecutiveStage alias. Used by auth and the OS shell.",
  },
  {
    name: "WorkspaceMain",
    purpose: "Main landmark of the operating workspace.",
    responsibilities: "id=main-content. Scroll. Host WorkspaceCanvas.",
    allowedChildren: "WorkspaceCanvas, PageRoot, product screens",
    forbiddenChildren: "NavigationRail, Toolbar",
    responsive: "Fills the stage below the toolbar.",
    accessibility: "One main. tabIndex=-1 for skip.",
    tokens: [],
    example: "WorkspaceMain > children",
    migration: "Moved from OsShell <main>.",
  },
  {
    name: "BrandRail",
    purpose: "Authentication brand column.",
    responsibilities: "measure.sm, measure.md from extra-large. Hidden below large.",
    allowedChildren: "VentureMark, Stack, captions",
    forbiddenChildren: "Workspace navigation items, command lists",
    responsive: "Hidden below large. Wider from extra-large.",
    accessibility: "aside. Not primary navigation.",
    tokens: ["--ids-foundation-layout-rail", "--ids-foundation-layout-rail-wide"],
    example: "BrandRail > VentureMark + Stack",
    migration: "ExecutiveRail alias. Authentication reference only.",
  },
] as const;

export const LAYOUT_PRIMITIVE_NAMES = LAYOUT_PRIMITIVES.map((item) => item.name);
